### ISSUE TITLE
Cannot combine params and body?

### ISSUE THREAD

**Issue by anaxagoras** [elasticsearch/elasticsearch-perl#55]
I have a remote node that I am attempting to connect to that requires an api key as a URL parameter in addition to the body in order to get it to work.

The code is as follows:

```perl
#!/usr/bin/perl
use v5.14;
use warnings;
use Search::Elasticsearch;
use Data::Dumper;

my $API_KEY='API_KEY';

my $ES = Search::Elasticsearch->new(
    cxn_pool => 'Static::NoPing',
    nodes => [{
        scheme => 'https',
        host => 'service.host.com',
        port => 443,
        path => '/api/es/a_path',
    }],
    #send_get_body_as => 'POST',
    trace_to => 'Stdout',
    log_to => 'Stdout',
);

my $res = $ES->search(
    params => {
        api_key => $API_KEY,
    },
    body        => {
        query       => {
            bool => {
                must => {
                    query_string => {
                        default_field => "_all",
                        query => "thisisasitethatdoesntexist.com",
                        default_operator => "AND"
                    }
                }
            }
        }
    }
);

print Dumper($res);
```

The generated curl is:

```
# Request to: https://service.host.com:443/api/es/a_path
curl -XGET 'http://localhost:9200/_search?api_key=API_KEY&pretty=1' -d '
{
   "query" : {
      "bool" : {
         "must" : {
            "query_string" : {
               "query" : "thisisasitethatdoesntexist.com",
               "default_field" : "_all",
               "default_operator" : "AND"
            }
         }
      }
   }
}
'
```
When I replace localhost and the path with the proper host and path and run the curl command directly from the command line, I get zero hits back, which is what I expect.  If I run the above perl, however, I get many millions of results back, which is exactly the same as what I get when I remove the body from the curl query (```-d ''```). So it seems that the combination of params and body causes body to get eaten?  I looked at the code, but I couldn't find where this might be happening.  I have also tried the commented-out ```send_get_body_as => 'POST',```, but the service flatly refuses POSTS, which I've been informed is a sort of low-hanging fruit security measure to prevent mutating methods.

**Comment by clintongormley** [comment]
Hiya

OK I tried the above out and it all seems to be working correctly.  I'm assuming you have the latest version of Search::Elasticsearch installed (cos there were some https bugs which have been fixed).

Try using this request:

    my $res = $ES->search(
        params => {
            api_key => $API_KEY,
        },
        body        => {
            size => 0,
            query => {
                term => {
                    foo => 'bar'
                }
            }
        }
    );

That should return zero hits and a total of zero (assuming you don't have a field "foo" which contains "bar".

Failing that, you may want to install Search::Elasticsearch::Cxn::NetCurl, and edit that module to uncomment this line:

      # $handle->setopt( CURLOPT_VERBOSE,     1 );

Use it as:

    my $ES = Search::Elasticsearch->new(
        cxn_pool => 'Static::NoPing',
        cxn => 'NetCurl', 
        timeout => 10,
        ....

That will tell you exactly what is being sent to the remote server  (although it won't show you the body itself, just how many bytes).

**Comment by anaxagoras** [comment]
I just upgraded from 1.17 to 1.19, but the problem persists, alas.

```size => 0``` did not seem to have any noticeable effect.  I'll use Cxn::NetCurl and report back.

**Comment by anaxagoras** [comment]
```
* Hostname was NOT found in DNS cache
*   Trying <IP>…
* TCP_NODELAY set
* Connected to <HOST> (<IP>) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: <HOST>
* Server certificate: GeoTrust Extended Validation SSL CA - G2
* Server certificate: GeoTrust Primary Certification Authority
> GET /api/es/SOME_PATH/_search?api_key=<API KEY> HTTP/1.1
Host: <HOST>
Accept: */*
Content-Type: application/json
Content-Length: 126

* upload completely sent off: 126 out of 126 bytes
< HTTP/1.1 200 OK
* Server nginx/1.4.7 is not blacklisted
< Server: nginx/1.4.7
< Date: Wed, 21 Jan 2015 22:14:39 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 362371
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubdomains
<
* Connection #0 to host <HOST> left intact
Current cxns: ["https://<HOST>/api/es/SOME_PATH“]
# Request to: https://<HOST>/api/es/SOME_PATH
curl -XGET 'http://localhost:9200/_search?api_key=<API KEY>&pretty=1' -d '
{
   "query" : {
      "bool" : {
         "must" : {
            "query_string" : {
               "default_operator" : "AND",
               "query" : "asdasdasdasdasdasdasd",
               "default_field" : "_all"
            }
         }
      }
   }
}
'
```

**Comment by clintongormley** [comment]
OK - so it looks like everything is being sent correctly.  Perhaps what you want to do is to compare the command line curl request (with `--verbose`) that works with the debug output from the Perl request, to figure out where the difference is.  Perhaps it is do with some headers?

**Comment by anaxagoras** [comment]
Here's the verbose output from the command line version:
```
* Hostname was NOT found in DNS cache
*   Trying <IP>...
* Connected to <HOST> (<IP>) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: <HOST>
* Server certificate: <CERT STUFF>
* Server certificate: <CERT STUFF>
> GET /api/es/SOME_PATH/_search?api_key=<API KEY>&pretty=1 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: <HOST>
> Accept: */*
> Content-Length: 255
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 255 out of 255 bytes
< HTTP/1.1 200 OK
* Server nginx/1.4.7 is not blacklisted
< Server: nginx/1.4.7
< Date: Mon, 26 Jan 2015 17:23:17 GMT
< Content-Type: application/json; charset=UTF-8
< Content-Length: 196
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubdomains
<
{
  "took" : 28,
  "timed_out" : false,
  "_shards" : {
    "total" : 20,
    "successful" : 20,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
* Connection #0 to host <HOST> left intact
```

**Comment by anaxagoras** [comment]
Ah, that seems to be it! On a lark, I added ```-H'Content-Type: application/json'``` to the command-line curl, and now I get ~3 million hits. If I remove it, my search number changes depending upon the search. It seems this server does not like this header. Is there any way to suppress this behavior on initialization?

**Comment by clintongormley** [comment]
Hmm, there isn't, but possibly I could provide a callback for altering headers...

**Comment by clintongormley** [comment]
(or the service you're using could fix their bug)

**Comment by anaxagoras** [comment]
I'll submit a bug report to them, but if I can't get a decent response back, a callback might be nice. I hope it's not required. In the meantime, it seems to me that the only bug we've got for sure here is that the generated curl doesn't include ```-H'Content-Type: <whatever your serializer sets>'```

**Comment by anaxagoras** [comment]
Okay, it was a proxy-type bug after all.  While I'm thankful Search::Elasticsearch didn't specify a header for content type in the debug output (as it helped me track down the bug in this admittedly rare case), I'm still debating whether or not I'd consider it a bug that it didn't.  I'll leave the answer to that up to you, but this issue can be closed now. Thanks for your help.

**Comment by clintongormley** [comment]
Yeah, including the headers in the trace output would be tricky, as each backend adds its own headers which we'd somehow need to extract.  And I think it'd add a lot of noise for no real purpose.  Glad you found the issue - I'll go ahead and close.
